/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EDITOR;

import static EDITOR.myWord.endpoint;
import java.awt.GraphicsEnvironment;
import java.io.StringReader;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.ElementIterator;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.html.HTML;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author oscarito
 */
public class PrincipalScreen extends javax.swing.JFrame implements Runnable{
    FILE myFile;
    int idUser;
    boolean sharedFiles;
    public class filePrivilege {
        int idUser, idFile, privilege;
        String nickName;

        public filePrivilege(int idUser, int idFile, int privilege, String nickName) {
            this.idUser = idUser;
            this.idFile = idFile;
            this.privilege = privilege;
            this.nickName = nickName;
        }
        public String toString() {
            return this.nickName;
        }
        
    }
    public PrincipalScreen(int idUser) {
        this.idUser = idUser;
        initComponents();
        setFonts();
        myFile = new FILE(idUser, this.txtDocumento);
        
    }
    /**
     * Creates new form PrincipalScreen
     */
    
    public PrincipalScreen() {
        initComponents();
        setFonts();
        myFile = new FILE(1, this.txtDocumento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdOpenFile = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiles = new javax.swing.JTable();
        btnDeleteFile = new javax.swing.JButton();
        btnExportTo1 = new javax.swing.JButton();
        btnShare1 = new javax.swing.JButton();
        btnLogFile1 = new javax.swing.JButton();
        btnOpenFile1 = new javax.swing.JButton();
        jdShareFile = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();
        chkRead = new javax.swing.JCheckBox();
        chkWrite = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnNewFile = new javax.swing.JButton();
        btnOpenFile = new javax.swing.JButton();
        btnCompleteLog = new javax.swing.JButton();
        btnMyFiles = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSettings = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        btnExportTo = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnLogFile = new javax.swing.JButton();
        btnShare = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnCopy = new javax.swing.JButton();
        btnCut = new javax.swing.JButton();
        btnPaste = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cmbFonts = new javax.swing.JComboBox<>();
        cmbSizeFont = new javax.swing.JComboBox<>();
        btnBold = new javax.swing.JButton();
        btnItalic = new javax.swing.JButton();
        btnUnderline = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnAlignCenter = new javax.swing.JButton();
        btnAlignLeft = new javax.swing.JButton();
        btnAlignJustified = new javax.swing.JButton();
        btnAlignRight = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDocumento = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jdOpenFile.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jdOpenFile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jdOpenFileComponentShown(evt);
            }
        });

        tblFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Creation User", "Creation Date", "Modification Date", "Content", "Privilege"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFiles);

        btnDeleteFile.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/deleteFile.png")); // NOI18N
        btnDeleteFile.setToolTipText("Delete File");
        btnDeleteFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteFileMouseClicked(evt);
            }
        });

        btnExportTo1.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/exportTo.png")); // NOI18N
        btnExportTo1.setToolTipText("Export To");
        btnExportTo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportTo1MouseClicked(evt);
            }
        });

        btnShare1.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/shareFile.png")); // NOI18N
        btnShare1.setToolTipText("Share File");
        btnShare1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShare1MouseClicked(evt);
            }
        });

        btnLogFile1.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/logFile.png")); // NOI18N
        btnLogFile1.setToolTipText("View Log File");

        btnOpenFile1.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/openFile.png")); // NOI18N
        btnOpenFile1.setToolTipText("Open File");
        btnOpenFile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenFile1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdOpenFileLayout = new javax.swing.GroupLayout(jdOpenFile.getContentPane());
        jdOpenFile.getContentPane().setLayout(jdOpenFileLayout);
        jdOpenFileLayout.setHorizontalGroup(
            jdOpenFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdOpenFileLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jdOpenFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOpenFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShare1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jdOpenFileLayout.setVerticalGroup(
            jdOpenFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdOpenFileLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jdOpenFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdOpenFileLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(btnOpenFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnShare1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnLogFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jdShareFile.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jdShareFile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jdShareFileComponentShown(evt);
            }
        });

        lstUsers.setModel(new DefaultListModel());
        lstUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstUsersMouseClicked(evt);
            }
        });
        lstUsers.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lstUsersPropertyChange(evt);
            }
        });
        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstUsers);

        chkRead.setText("Read");

        chkWrite.setText("Write/Read");
        chkWrite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkWriteItemStateChanged(evt);
            }
        });

        jButton2.setText("Share");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdShareFileLayout = new javax.swing.GroupLayout(jdShareFile.getContentPane());
        jdShareFile.getContentPane().setLayout(jdShareFileLayout);
        jdShareFileLayout.setHorizontalGroup(
            jdShareFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdShareFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jdShareFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkWrite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkRead)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jdShareFileLayout.setVerticalGroup(
            jdShareFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdShareFileLayout.createSequentialGroup()
                .addGroup(jdShareFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdShareFileLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdShareFileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkRead)
                        .addGap(18, 18, 18)
                        .addComponent(chkWrite)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Files"));

        btnNewFile.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/newFile.png")); // NOI18N
        btnNewFile.setToolTipText("New File");
        btnNewFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewFileMouseClicked(evt);
            }
        });

        btnOpenFile.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/openFile.png")); // NOI18N
        btnOpenFile.setToolTipText("Open File");
        btnOpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenFileMouseClicked(evt);
            }
        });

        btnCompleteLog.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/logFile.png")); // NOI18N
        btnCompleteLog.setToolTipText("Open Complete Log");
        btnCompleteLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompleteLogMouseClicked(evt);
            }
        });
        btnCompleteLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteLogActionPerformed(evt);
            }
        });

        btnMyFiles.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/myFiles.png")); // NOI18N
        btnMyFiles.setToolTipText("Open My Files");
        btnMyFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMyFilesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnNewFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMyFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnCompleteLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNewFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCompleteLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMyFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));

        btnSettings.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/configuration.png")); // NOI18N
        btnSettings.setToolTipText("Settings");

        btnLogout.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/logout.png")); // NOI18N
        btnLogout.setToolTipText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MyWord", jPanel4);

        btnSave.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/save.png")); // NOI18N
        btnSave.setToolTipText("Save File");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnSaveAs.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/saveAs.png")); // NOI18N
        btnSaveAs.setToolTipText("Save File As");

        btnExportTo.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/exportTo.png")); // NOI18N
        btnExportTo.setToolTipText("Export To");

        btnDelete.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/deleteFile.png")); // NOI18N
        btnDelete.setToolTipText("Delete File");

        btnLogFile.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/logFile.png")); // NOI18N
        btnLogFile.setToolTipText("View Log File");

        btnShare.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/shareFile.png")); // NOI18N
        btnShare.setToolTipText("Share File");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnSaveAs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnExportTo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnShare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportTo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveAs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("File", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Clipboard"));
        jPanel5.setAlignmentY(0.0F);

        btnCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EDITOR/copy.png"))); // NOI18N
        btnCopy.setText("Copy");
        btnCopy.setToolTipText("Copy");

        btnCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EDITOR/cut.png"))); // NOI18N
        btnCut.setText("Cut");
        btnCut.setToolTipText("Cut");

        btnPaste.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/paste.png")); // NOI18N
        btnPaste.setText("Paste");
        btnPaste.setToolTipText("Paste");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPaste, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
            .addComponent(btnCopy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaste, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Font"));

        cmbFonts.setToolTipText("Style Font");
        cmbFonts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFontsItemStateChanged(evt);
            }
        });

        cmbSizeFont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "18", "20", "22", "24", "26", "28", "30", "32", "36", "40", "44" }));
        cmbSizeFont.setToolTipText("Font Size");
        cmbSizeFont.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSizeFontItemStateChanged(evt);
            }
        });

        btnBold.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnBold.setText("B");
        btnBold.setToolTipText("Bold");
        btnBold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBoldMouseClicked(evt);
            }
        });

        btnItalic.setFont(new java.awt.Font("Ubuntu", 2, 13)); // NOI18N
        btnItalic.setText("I");
        btnItalic.setToolTipText("Italic");
        btnItalic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnItalicMouseClicked(evt);
            }
        });

        btnUnderline.setText("<html><u>U</u></html>");
        btnUnderline.setToolTipText("Underline");
        btnUnderline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnderlineMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBold, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnItalic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbFonts, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSizeFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFonts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSizeFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBold, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItalic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Paragraph"));

        btnAlignCenter.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/alignCenter.png")); // NOI18N
        btnAlignCenter.setToolTipText("Align Center");
        btnAlignCenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlignCenterMouseClicked(evt);
            }
        });

        btnAlignLeft.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/alignLeft.png")); // NOI18N
        btnAlignLeft.setToolTipText("Align Left");
        btnAlignLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlignLeftMouseClicked(evt);
            }
        });

        btnAlignJustified.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/alignJustified.png")); // NOI18N
        btnAlignJustified.setToolTipText("Justified");
        btnAlignJustified.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlignJustifiedMouseClicked(evt);
            }
        });

        btnAlignRight.setIcon(new javax.swing.ImageIcon("/media/oscarito/Datos/UNITEC/2016/IV PERIODO/ESTRUCTURA DE DATOS II/MyWord/MyWord/src/EDITOR/alignRight.png")); // NOI18N
        btnAlignRight.setToolTipText("Align Right");
        btnAlignRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlignRightMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnAlignLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnAlignCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAlignRight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAlignJustified, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlignCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlignJustified, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlignRight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAlignLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Text", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, Short.MAX_VALUE)
        );

        txtDocumento.setContentType("text/html"); // NOI18N
        txtDocumento.setText("");
        txtDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDocumentoMouseClicked(evt);
            }
        });
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtDocumento);
        txtDocumento.getAccessibleContext().setAccessibleName("");

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);

        jMenu3.setText("Export To");

        jMenuItem3.setText("Docx");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("RTF");
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnBoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoldMouseClicked
        setTextAttribute("bold");
    }//GEN-LAST:event_btnBoldMouseClicked

    private void btnItalicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItalicMouseClicked
        setTextAttribute("italic");
    }//GEN-LAST:event_btnItalicMouseClicked

    private void btnUnderlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnderlineMouseClicked
        setTextAttribute("underline");
    }//GEN-LAST:event_btnUnderlineMouseClicked

    private void cmbFontsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFontsItemStateChanged
        setTextAttribute("fontFamily", this.cmbFonts.getSelectedItem());
    }//GEN-LAST:event_cmbFontsItemStateChanged

    private void cmbSizeFontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSizeFontItemStateChanged
        setTextAttribute("fontSize", this.cmbSizeFont.getSelectedItem());
    }//GEN-LAST:event_cmbSizeFontItemStateChanged

    private void btnAlignCenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlignCenterMouseClicked
        setTextAttribute("align", "center");
    }//GEN-LAST:event_btnAlignCenterMouseClicked

    private void btnAlignLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlignLeftMouseClicked
        setTextAttribute("align", "left");
    }//GEN-LAST:event_btnAlignLeftMouseClicked

    private void btnAlignRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlignRightMouseClicked
        setTextAttribute("align", "right");
    }//GEN-LAST:event_btnAlignRightMouseClicked

    private void btnAlignJustifiedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlignJustifiedMouseClicked
        setTextAttribute("align", "justified");
    }//GEN-LAST:event_btnAlignJustifiedMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        myFile.toJSON();
//        test();
//        byte[] text = Base64.getEncoder().encode(this.txtDocumento.getText().getBytes());
//        System.out.println("TEST BASE64" + new String(Base64.getDecoder().decode(text)));
//        read("test", this.txtDocumento.getText());
//        System.out.println(this.txtDocumento.getText());
    }//GEN-LAST:event_jButton1MouseClicked

    
    /**
     * Open a dialog to ask the name of the new file and create in DB
     * @param evt 
     */
    private void btnNewFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewFileMouseClicked
        String name = JOptionPane.showInputDialog("Name: ", "New File");
        if (name == null) {
            return;
        }
        
        if (name.isEmpty()) {
            return;
        }
        
        JSONObject object = new JSONObject();
        object.put("NAME", name);
        Object[] response = endpoint("createFile", object);
        if ((boolean)response[0] == true) {
            JSONObject jsonFile = (JSONObject)response[1];
            myFile.setId(Integer.parseInt(jsonFile.get("ID").toString()));
            myFile.setName(jsonFile.get("NAME").toString());
        }
    }//GEN-LAST:event_btnNewFileMouseClicked

    /**
     * List my files
     * @param evt 
     */
    private void jdOpenFileComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdOpenFileComponentShown
        
        DefaultTableModel tbl = (DefaultTableModel)this.tblFiles.getModel();
        tbl.setRowCount(0);
        JSONArray response = (JSONArray)endpoint(this.sharedFiles ? "readSharedFiles" : "readFiles", null)[1];
        this.btnDeleteFile.setEnabled(!this.sharedFiles);
//        this.btnExportTo1.setEnabled(this.sharedFiles);
        this.btnShare1.setEnabled(!this.sharedFiles);
        this.btnLogFile1.setEnabled(!this.sharedFiles);
 
//        JSONArray response = (JSONArray)endpoint("readSharedFiles", null)[1];
        for (Object object : response) {
            JSONObject file = (JSONObject)object;
            tbl.addRow(new Object[] {
                Integer.parseInt(file.get("ID").toString()),
                file.get("NAME"),
                file.get("CREATION_USER"),
                file.get("CREATION_DATE"),
                file.get("MODIFICATION_DATE"),
                file.get("CONTENT"),
                file.get("PRIVILEGE") != null ? Integer.parseInt(file.get("PRIVILEGE").toString()) : 2,
            });
        }
//        System.out.println("@FILES" + response.length);
        
    }//GEN-LAST:event_jdOpenFileComponentShown

    private void btnOpenFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFileMouseClicked
        this.sharedFiles = false;
        this.jdOpenFile.pack();
        this.jdOpenFile.setLocationRelativeTo(this);
        this.jdOpenFile.setVisible(true);
    }//GEN-LAST:event_btnOpenFileMouseClicked
        public void deleteFiles(int[] indexFiles) {
        DefaultTableModel model = (DefaultTableModel)this.tblFiles.getModel();
        JSONArray ids = new JSONArray();
        JSONObject object = new JSONObject();
        for (int i = 0; i < indexFiles.length; i++) {
            ids.add((int)model.getValueAt(indexFiles[i], 0));
//            System.out.println("@ids[i]" + ids[i]);
        }
        object.put("IDS", ids);
        endpoint("deleteFiles", object);
//        object.put("ID", ids.get(0));
//        endpoint("readUsersXFile", object);
    }
    private void btnDeleteFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteFileMouseClicked
        deleteFiles(this.tblFiles.getSelectedRows());
        
    }//GEN-LAST:event_btnDeleteFileMouseClicked

    private void btnExportTo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportTo1MouseClicked
        
    }//GEN-LAST:event_btnExportTo1MouseClicked

    private void txtDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDocumentoMouseClicked
        System.out.println(this.txtDocumento.getCaretPosition());
    }//GEN-LAST:event_txtDocumentoMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        myFile.toJSON();
        myFile.start();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void jdShareFileComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdShareFileComponentShown
    }//GEN-LAST:event_jdShareFileComponentShown

    private void btnShare1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShare1MouseClicked
        // TODO add your handling code here:
        int indexFile = this.tblFiles.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)this.tblFiles.getModel();
        JSONObject object = new JSONObject();
        int idFile = (int)model.getValueAt(indexFile, 0);
//        object.put("IDS", ids);
//        endpoint("deleteFiles", object);
        object.put("ID", idFile);
        Object[] response = endpoint("readUsersXFile", object);
        if ((boolean)response[0] == true) {
            this.jdShareFile.pack();
            this.jdShareFile.setLocationRelativeTo(this);
            this.jdShareFile.setVisible(true);
            
            JSONArray files = (JSONArray)response[1];
            
            for (Object file : files) {
                JSONObject JSONfile = (JSONObject)file;
                DefaultListModel modelo = (DefaultListModel)this.lstUsers.getModel();
                modelo.clear();
                System.out.println("@PRIVILEGE = " + JSONfile.toJSONString());
                modelo.addElement(new filePrivilege(
                        Integer.parseInt(JSONfile.get("ID").toString()),
                        idFile,
                        JSONfile.get("PRIVILEGE") != null ? Integer.parseInt(JSONfile.get("PRIVILEGE").toString()) : 0,
                        JSONfile.get("NICKNAME").toString()
                ));
            }
        }
    }//GEN-LAST:event_btnShare1MouseClicked

    private void lstUsersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lstUsersPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lstUsersPropertyChange

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsersValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstUsersValueChanged

    private void lstUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstUsersMouseClicked
        // TODO add your handling code here:
        try {
            Object[] selected = this.lstUsers.getSelectedValues();
            
            if (selected.length == 0) return;
            
            filePrivilege privilege = ((filePrivilege)selected[0]);
            
//            if (privilege.privilege == 1) {
                this.chkRead.setSelected(privilege.privilege != 0);
                this.chkWrite.setSelected(privilege.privilege == 2);
//            }
//            System.out.println("@SELECTED " + .toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lstUsersMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        Object[] selected = this.lstUsers.getSelectedValues();

        if (selected.length == 0) return;

        filePrivilege privilege = ((filePrivilege)selected[0]);
        
        JSONObject object = new JSONObject();
        
        object.put("idFile", privilege.idFile);
        object.put("idUser", privilege.idUser);
        
        if (this.chkWrite.isSelected()) {
            object.put("privilege", 2);
        } else if (this.chkRead.isSelected()) {
            object.put("privilege", 1);
        } else {
            object.put("privilege", 0);
        }
        endpoint("shareFile",object);
    }//GEN-LAST:event_jButton2MouseClicked

    private void chkWriteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkWriteItemStateChanged
        // TODO add your handling code here:
        this.chkRead.setSelected(true);
    }//GEN-LAST:event_chkWriteItemStateChanged

    private void btnMyFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMyFilesMouseClicked
        // TODO add your handling code here:
        this.sharedFiles = true;
        this.jdOpenFile.pack();
        this.jdOpenFile.setLocationRelativeTo(this);
        this.jdOpenFile.setVisible(true);
    }//GEN-LAST:event_btnMyFilesMouseClicked

    private void btnOpenFile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenFile1MouseClicked
        // TODO add your handling code here:
        JSONParser jsonParser = new JSONParser();
        JSONObject object = new JSONObject();
        DefaultTableModel model = (DefaultTableModel)this.tblFiles.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this.jdOpenFile, "You didn't select any file", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        int idFile = (int)model.getValueAt(this.tblFiles.getSelectedRow(), 0);
        int privilege = (int)model.getValueAt(this.tblFiles.getSelectedRow(), 6);
        
        object.put("ID", idFile);
        Object[] response = endpoint("openFile", object);
        if ((boolean)response[0] == true) {
            myFile.setId(idFile);
            myFile.setNameFile(model.getValueAt(this.tblFiles.getSelectedRow(), 1).toString());
            myFile.setCreationUser(Integer.parseInt(model.getValueAt(this.tblFiles.getSelectedRow(), 2).toString()));
            
            if (privilege == 1)
                this.txtDocumento.disable();
            else
                this.txtDocumento.enable();
            
            this.txtDocumento.setEditable(privilege != 1);
            try {
                myFile.renderText((JSONArray)jsonParser.parse(model.getValueAt(this.tblFiles.getSelectedRow(), 5).toString()));
            } catch (ParseException ex) {
//                ex.printStackTrace();
            }
            myFile.start();
        }
    }//GEN-LAST:event_btnOpenFile1MouseClicked

    private void btnCompleteLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompleteLogActionPerformed

    private void btnCompleteLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteLogMouseClicked
        // TODO add your handling code here:
        new LOG("getCompleteLog").show();
    }//GEN-LAST:event_btnCompleteLogMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LOGIN(null, true).show();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoKeyReleased
    public void test () {
        HTMLEditorKit htmlKit = new HTMLEditorKit();
        HTMLDocument htmlDoc = (HTMLDocument) htmlKit.createDefaultDocument();
        setTextAttribute("id", "1");
        try {
            htmlKit.read(new StringReader(this.txtDocumento.getText()), htmlDoc, 0);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        // Parse
        ElementIterator iterator = new ElementIterator(htmlDoc);
        Element element;
        while ((element = iterator.next()) != null) {
            AttributeSet as = element.getAttributes();
            Object name = as.getAttribute(StyleConstants.NameAttribute);
            Object id = as.getAttribute("id");
            if (name == HTML.Tag.CONTENT || name == HTML.Tag.P) {
                System.out.println("Id " + id);
                StringBuffer sb = new StringBuffer();
                sb.append(name).append(": ").append(id);
                int count = element.getElementCount();
                for (int i = 0; i < count; i++) {
                    Element child = element.getElement(i);
                    int startOffset = child.getStartOffset();
                    int endOffset = child.getEndOffset();
                    int length = endOffset - startOffset;
                    try {
                        sb.append(htmlDoc.getText(startOffset, length));
                        
                    } catch (Exception e) {
            System.out.println(e.toString());
                    }
                }
                System.out.println(sb);
            }
        }
    }
    /**
     * 
     * @param attributeType 
     * @param parameter 
     */
    public void setTextAttribute(String attributeType, Object parameter) {

        int start = txtDocumento.getSelectionStart();
        int end = txtDocumento.getSelectionEnd();
//        System.out.println("Start = " + start);
//        System.out.println("End = " + end);
        if (start == end) {
//            try {
//                start = Utilities.getRowStart(txtDocumento, txtDocumento.getCaretPosition());
//                end = Utilities.getRowEnd(txtDocumento, txtDocumento.getCaretPosition());
//            } catch (Exception e) {
//            }
//            if (end == 0) {
                return;
//            }
        }
        Document test = this.txtDocumento.getDocument();
        
        StyledDocument doc = (StyledDocument) txtDocumento.getDocument();
        Element element = doc.getCharacterElement(start);
        AttributeSet as = null;
        if (attributeType.equals("align")) {
            as = this.txtDocumento.getInputAttributes();
        } else {
            as = element.getAttributes();
        }
        MutableAttributeSet asNew = new SimpleAttributeSet(as.copyAttributes());
        if (attributeType.equals("bold")) {
            StyleConstants.setBold(asNew, !StyleConstants.isBold(as));
        } else if (attributeType.equals("underline")) {
            StyleConstants.setUnderline(asNew, !StyleConstants.isUnderline(as));
        } else if (attributeType.equals("italic")) {
            StyleConstants.setItalic(asNew, !StyleConstants.isItalic(as));
        } else if (attributeType.equals("fontFamily")) {
            StyleConstants.setFontFamily(asNew, (String)parameter);
        } else if (attributeType.equals("fontSize")) {
            StyleConstants.setFontSize(asNew, Integer.parseInt((String)parameter));
        } else if (attributeType.equals("align")) {
            String alignTo = (String)parameter;
            if (alignTo.equals("center")) {
                StyleConstants.setAlignment(asNew, StyleConstants.ALIGN_CENTER);
            } else if (alignTo.equals("left")) {
                StyleConstants.setAlignment(asNew, StyleConstants.ALIGN_LEFT);
            } else if (alignTo.equals("right")) {
                StyleConstants.setAlignment(asNew, StyleConstants.ALIGN_RIGHT);
            } else if (alignTo.equals("justified")) {
                StyleConstants.setAlignment(asNew, StyleConstants.ALIGN_JUSTIFIED);
            }
            doc.setParagraphAttributes(start, end - start - 1, asNew, true);
//            return;
        } else {
            System.out.println("attributeType" + attributeType);
            System.out.println("attributeType" + parameter);
            asNew.addAttribute(attributeType, parameter);
            doc.setParagraphAttributes(start, end - start, asNew, true);
        }
        doc.setCharacterAttributes(start, end - start, asNew, true);
//        System.out.println(this.txtDocumento.getText());
    }
    
    /**
     * 
     * @param attributeType 
     */
    public void setTextAttribute(String attributeType) {
        setTextAttribute(attributeType, null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        System.out.println("HOLA TODOSs");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalScreen().setVisible(true);
            }
        });
    }
    
    public void setFonts() {
        String[] fontNames=GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
//        System.out.println(Arrays.toString(fontNames));
//        JLabel lbl = new JLabel("<u>U</u>");
//        this.btnUnderline.setLabel("<html><u>U</u></html>");
        for (String fontName : fontNames) {
            this.cmbFonts.addItem(fontName);
        }
        try {
            DefaultComboBoxModel fontsModel = (DefaultComboBoxModel)this.cmbFonts.getModel();
            fontsModel.setSelectedItem("DejaVu Sans");
            
            DefaultComboBoxModel fontSizeModel = (DefaultComboBoxModel)this.cmbSizeFont.getModel();
            fontSizeModel.setSelectedItem("14");
        } catch (Exception e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlignCenter;
    private javax.swing.JButton btnAlignJustified;
    private javax.swing.JButton btnAlignLeft;
    private javax.swing.JButton btnAlignRight;
    private javax.swing.JButton btnBold;
    private javax.swing.JButton btnCompleteLog;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnCut;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteFile;
    private javax.swing.JButton btnExportTo;
    private javax.swing.JButton btnExportTo1;
    private javax.swing.JButton btnItalic;
    private javax.swing.JButton btnLogFile;
    private javax.swing.JButton btnLogFile1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyFiles;
    private javax.swing.JButton btnNewFile;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnOpenFile1;
    private javax.swing.JButton btnPaste;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnShare;
    private javax.swing.JButton btnShare1;
    private javax.swing.JButton btnUnderline;
    private javax.swing.JCheckBox chkRead;
    private javax.swing.JCheckBox chkWrite;
    private javax.swing.JComboBox<String> cmbFonts;
    private javax.swing.JComboBox<String> cmbSizeFont;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jdOpenFile;
    private javax.swing.JDialog jdShareFile;
    private javax.swing.JList<String> lstUsers;
    private javax.swing.JTable tblFiles;
    private javax.swing.JTextPane txtDocumento;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
